<?php


DB::table('potencia')->insert(['no_continente'   => 'Ilhas Brtânicas','no_potencia'     => 'Grand Lodge of Ireland']);
DB::table('potencia')->insert(['no_continente'   => 'Ilhas Brtânicas','no_potencia'     => 'Grand Lodge of Scotland']);

DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Albania']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Andorra']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Armenia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Austria']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Regular Grand Lodge of Belgium']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Bosnia and Herzegovina']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'United Grand Lodge of Bulgaria']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Croatia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Cyprus']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Czech Republic']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Denmark (Danish Order of Freemasons)']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Estonia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Finland']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grande Loge Nationale Française']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'United Grand Lodges of Germany']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Greece']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Symbolic Grand Lodge of Hungary']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Iceland (Icelandic Order of Freemasons)']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Regular Grand Lodge of Italy']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Latvia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Lithuania']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Luxembourg']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Macedonia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Sovereign Grand Lodge of Malta']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Moldova']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'National Regular Grand Lodge of the Principality of Monaco']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Montenegro']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand East Lodge of Netherlands']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Norway (Norwegian Order of Freemasons)']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'National Grand Lodge of Poland']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Portugal (Legal)']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'National Grand Lodge of Romania']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Russia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of the Most Serene Republic of San Marino']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Regular Grand Lodge of Serbia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Slovakia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Slovenia']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Spain']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Sweden (Swedish Order of Freemasons)']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge Alpina of Switzerland']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Turkey']);
DB::table('potencia')->insert(['no_continente'   => 'Europa','no_potencia'     => 'Grand Lodge of Ukraine']);

Africa

DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Benin']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Burkina Faso']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Cameroon']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Congo*']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Gabon']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Ghana']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'National Grand Lodge of Guinea']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Ivory Coast']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of the Republic of Liberia']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'National Grand Lodge of Madagascar']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'National Grand Lodge of Mali']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Mauritius']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Regular Grand Lodge of the Kingdom of Morocco']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Nigeria']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of Senegal']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'Grand Lodge of South Africa']);
DB::table('potencia')->insert(['no_continente'   => 'Africa','no_potencia'     => 'National Grand Lodge of Togo']);


DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'United Grand Lodge of New South Wales and the Australian Capital Territory']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'Grand Lodge of New Zealand']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'Grand Lodge of Queensland']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'Grand Lodge of South Australia and the Northern Territory']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'Grand Lodge of Tasmania']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'United Grand Lodge of Victoria']);
DB::table('potencia')->insert(['no_continente'   => 'Asia e Australia','no_potencia'     => 'Grand Lodge of Western Australia']);


DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Alberta']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of British Columbia and Yukon']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Canada (in the Province of Ontario)']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Ontario']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Manitoba']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of New Brunswick']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Newfoundland and Labrador']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Nova Scotia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Prince Edward Island']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Quebec']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Saskatchewan']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Alabama']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Alaska']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Alaska']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Arizona']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Arizona']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Arkansas']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of California']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of California']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Colorado']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Colorado']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Connecticut']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Connecticut']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Delaware']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Delaware']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of the District of Columbia   [Washington DC]']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of the District of Columbia   [Washington DC]']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Florida']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Georgia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Hawaii']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Hawaii']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Idaho']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Illinois']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Illinois']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Indiana']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Indiana']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Iowa']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Iowa']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Kansas']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Kansas']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Kentucky']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Louisiana']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Maine']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Maryland']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Maryland']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Massachusetts']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Massachusetts']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Michigan']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Michigan']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Minnesota']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Minnesota']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Mississippi']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Missouri']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Missouri']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Montana']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Nebraska']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Nebraska']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Nevada']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Nevada']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of New Hampshire']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of New Jersey']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of New Jersey']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of New Mexico']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of the State of New Mexico']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of the State of New York']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of New York']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of North Carolina']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of North Carolina']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of North Dakota']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Ohio']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Ohio']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Oklahoma']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Oregon']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Oregon']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Pennsylvania']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Pennsylvania']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Rhode Island']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Rhode Island']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of South Carolina']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of South Dakota']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Tennessee']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Texas']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Texas']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Utah']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Vermont']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Virginia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Virginia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Washington']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Washington']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of West Virginia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Wisconsin']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Prince Hall Grand Lodge of Wisconsin']);
DB::table('potencia')->insert(['no_continente'   => 'América do Norte','no_potencia'     => 'Grand Lodge of Wyoming']);



DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Costa Rica']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Cuscatlan of El Salvador']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Guatemala']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'York Grand Lodge of Mexico']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Panama']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of the State of Vera Cruz']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Prince Hall Grand Lodge of the Commonwealth of the Bahamas']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Prince Hall Grand Lodge of the Caribbean and Jurisdiction']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Cuba']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of the Dominican Republic']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Orient of Haiti']);
DB::table('potencia')->insert(['no_continente'   => 'América Central','no_potencia'     => 'Grand Lodge of Puerto Rico']);



DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Argentina']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Bolivia']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Orient of Brazil']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the State of Espírito Santo']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the State of Mato Grosso Do Sul']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the State of Rio De Janeiro']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the State of Rio Grande do Sul']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the State of São Paulo']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Chile']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Colombia at Barranquilla']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Colombia at Bogota']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Colombia at Cali']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Colombia at Cartagena']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge Oriental of Colombia ‘Francisco de Paula Santander’']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Los Andes']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Ecuador']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Symbolic Grand Lodge of Paraguay']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Peru']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of Uruguay']);
DB::table('potencia')->insert(['no_continente'   => 'América do Sul','no_potencia'     => 'Grand Lodge of the Republic of Venezuela']);